
import Image from 'next/image';

import Head from 'next/head';
import Dashbord from '../components/Dashbord';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>netlify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashbord />
    </div>
  )
}
