
import Image from 'next/image';

import Head from 'next/head';
import Dashbord from '../components/Dashbord';

import { useSession } from "next-auth/react";
import { useRouter } from "next/router";
import Loader from '../components/Loader';


export default function Home() {
const router = useRouter();
const {status,data:session} = useSession({
  required: true,
  onUnauthenticated() {
    router.push("/auth/signin");
  },
});

if(status === "loading"){
  return <Loader />;
}

console.log(session);



  return (
    <div className="">
      <Head>
        <title>netlify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashbord />
    </div>
  )
}
